apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels:
    app: bg-app
    version: blue
spec:
  type: NodePort
  selector:
    app: bg-app
    version: blue
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30020